services:
  mysql:
    image: mysql:8
    container_name: authium-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authium
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authium-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authium?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork
    env_file:
      - .env.docker
volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
